#*****************************************************************************#
#    Copyright (C) 2014 Aali132                                               #
#    Copyright (C) 2020 Julian Xhokaxhiu                                      #
#                                                                             #
#    This file is part of Palmer                                              #
#                                                                             #
#    Palmer is free software: you can redistribute it and/or modify           #
#    it under the terms of the GNU General Public License as published by     #
#    the Free Software Foundation, either version 3 of the License            #
#                                                                             #
#    Palmer is distributed in the hope that it will be useful,                #
#    but WITHOUT ANY WARRANTY; without even the implied warranty of           #
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the            #
#    GNU General Public License for more details.                             #
#*****************************************************************************#

# Azure Pipeline YAML file

name: 0.8$(Rev:.r)

trigger:
  branches:
    include:
    - master
  tags:
    include:
    - '*'

variables:
  _IS_BUILD_CANARY: false
  _RELEASE_NAME: Palmer
  _RELEASE_VERSION: v0
  _RELEASE_CONFIGURATION: Release
  _BUILD_VERSION: $(Build.BuildNumber)
  _BUILD_BRANCH: $(Build.SourceBranch)

pool:
  vmImage: 'windows-latest'

steps:
- task: PowerShell@2
  displayName: 'Build $(_RELEASE_NAME)'
  inputs:
    filePath: .ci\build.ps1
- task: GitHubRelease@0
  condition: and(eq(variables._IS_BUILD_CANARY, 'true'), not(contains(variables._BUILD_BRANCH, 'refs/pull/')))
  displayName: 'Delete $(_RELEASE_NAME) Release (Canary)'
  continueOnError: true
  inputs:
    gitHubConnection: github_ci
    action: delete
    tagSource: manual
    tag: canary
- task: GitHubRelease@0
  condition: and(eq(variables._IS_BUILD_CANARY, 'true'), not(contains(variables._BUILD_BRANCH, 'refs/pull/')))
  displayName: 'Create $(_RELEASE_NAME) Release (Canary)'
  inputs:
    gitHubConnection: github_ci
    assets: .dist\*.zip
    isPreRelease: true
    tagSource: manual
    tag: canary
    title: $(_RELEASE_NAME)-$(_RELEASE_VERSION)
    releaseNotesSource: input
    releaseNotes: |
      This is a canary build. Please be aware it may be prone to crashing and is NOT tested by anyone. Use this build AT YOUR OWN RISK!
- task: GitHubRelease@0
  condition: and(eq(variables._IS_BUILD_CANARY, 'false'), not(contains(variables._BUILD_BRANCH, 'refs/pull/')))
  displayName: 'Create $(_RELEASE_NAME) Release (Stable)'
  inputs:
    gitHubConnection: github_ci
    assets: .dist\*.zip
    title: $(_RELEASE_NAME)-$(_RELEASE_VERSION)
